修正workflow

diff --git a/.github/workflows/auto-release-arm.yml b/.github/workflows/auto-release-arm.yml
--- a/.github/workflows/auto-release-arm.yml
+++ b/.github/workflows/auto-release-arm.yml
@@ -69,7 +69,7 @@ jobs:
       fail-fast: false
       matrix:
         platform: ${{ fromJson(github.event.inputs.platform_index == '' && '["windows","linux","macos"]' || github.event.inputs.platform_index == '1' && '["windows"]' || github.event.inputs.platform_index == '2' && '["linux"]' || github.event.inputs.platform_index == '3' && '["macos"]') }}
-    runs-on: ${{ matrix.platform == 'ubuntu-24.04-arm' }}
+    runs-on: ${{ matrix.platform == 'windows' && 'windows-11-arm' || matrix.platform == 'linux' && 'ubuntu-24.04-arm' || matrix.platform == 'macos' && 'macos-26' }}
     steps:
       - name: Checkout main repo into osu/
         uses: actions/checkout@v4
@@ -122,15 +122,15 @@ jobs:
         with:
           python-version: '3.x'
 
-      - name: Ensure arm64 runner
-        shell: bash
-        run: |
-          arch="$(uname -m)"
-          echo "Detected runner arch: ${arch}"
-          if [ "${arch}" != "arm64" ] && [ "${arch}" != "aarch64" ]; then
-            echo "::error::Expected arm64/aarch64 runner, but got ${arch}."
-            exit 1
-          fi
+      # - name: Ensure arm64 runner
+      #   shell: bash
+      #   run: |
+      #     arch="$(uname -m)"
+      #     echo "Detected runner arch: ${arch}"
+      #     if [ "${arch}" != "arm64" ] && [ "${arch}" != "aarch64" ]; then
+      #       echo "::error::Expected arm64/aarch64 runner, but got ${arch}."
+      #       exit 1
+      #     fi
 
       - name: Dotnet restore (desktop project)
         working-directory: osu
